### ISSUE TITLE
Merge Docker branch into Main branch

### ISSUE THREAD

**Issue by Deepakraj8055** [amosproj/amos2022ws01-firmware-scraper#119]
## User story
1. As a developer 
2. When i check the main branch
3. I want the Docker branch to be merged in the main branch 

4. As a User
5. When i want to run the firmware scraper
6. I want to see if it is Possible to run this scraper in both modes ? (TBD) Either run it directly on host or build with the docker container

## Acceptance criteria
* Docker branch is merged into the main branch
* If it is possible to run scraper in both modes, demo the possibilty that the scraper can be run directly on the host or can be build with the docker
* -m src.core runs
* writing into docker database works

## Definition of done (DoD)
* All the acceptance criteria have been met
* The code has been merged with the main one
* The documentation and Bill of Materials have been updated
* The code is complete and uploaded in GitHub
* Functionality has been reviewed

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by kirilzilla** [comment]
db_connector.py # os.getenv("MYSQL_PASSWORD")
port#
ENV MYSQL_USER= in Dockerfile src/
docker-compose.yml python -m src.core ; passwords
edit import to absolute import paths

**Comment by kirilzilla** [comment]
waiting for some developer feedback to merge into main 😇
