### ISSUE TITLE
Try the scraper and the firmware downloads on the server

### ISSUE THREAD

**Issue by Deepakraj8055** [amosproj/amos2022ws01-firmware-scraper#151]
## User story
1. As a user 
2. When the run the scraper
3. I want the vendor website being scraped, and downloads the firmware succesfully

## Acceptance criteria
* Installation is succesfull
* Scraper is running in the server without crashing
* Firmwares are succesfully downloaded

## Definition of done (DoD)
* All the acceptance criteria have been met
* The code has been merged with the main one
* The documentation and Bill of Materials have been updated
* The code is complete and uploaded in GitHub
* Functionality has been reviewed

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by kirilzilla** [comment]
installed docker and docker compose on ubuntu server.
started scraping, but current folder structure is broken for docker:
config.json vs src/config.json

**Comment by kirilzilla** [comment]
docker scraper works on server

**Comment by kirilzilla** [comment]
download function needs to be re-implemented, re-imageined.

- create correct folder structure (also for docker)
- download filtered on manufacturer
- updating downloaded_flag in DB after download

**Comment by kirilzilla** [comment]
it works. downloadable flag is file_path being NOT NULL
