### ISSUE TITLE
Check download links for all vendors

### ISSUE THREAD

**Issue by Deepakraj8055** [amosproj/amos2022ws01-firmware-scraper#161]
## User story
1. As a developer
2. I want to have check the download links for all the vendors
3. So that there are no issues and firmware can be downloaded successfully

## Acceptance criteria
* All firmware downloads links from all vendors checked for error
* Firmware downloaded where there are no errors
* Output a warning in case of an issue

## Definition of done (DoD)
* All the acceptance criteria have been met
* The code has been merged with the main one
* The documentation and Bill of Materials have been updated
* The code is complete and uploaded in GitHub
* Functionality has been reviewed

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by kirilzilla** [comment]
dlink has javascript outputs (in print)
