### ISSUE TITLE
Try to download every firmware on the server once

### ISSUE THREAD

**Issue by Deepakraj8055** [amosproj/amos2022ws01-firmware-scraper#162]
## User story
1. As a developer
2. I want to dowload every firmware from all the vendor once
3. So that we have a pool of firmwares available and stored

## Acceptance criteria
* All vendor firmwares are succesfully downloaded
* Error or error messages for the ones that couldnt be downloaded

## Definition of done (DoD)
* All the acceptance criteria have been met
* The code has been merged with the main one
* The documentation and Bill of Materials have been updated
* The code is complete and uploaded in GitHub
* Functionality has been reviewed

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by kirilzilla** [comment]
some vendors have issues downloading
