### ISSUE TITLE
Run every vendor without max_products limit

### ISSUE THREAD

**Issue by Deepakraj8055** [amosproj/amos2022ws01-firmware-scraper#163]
## User story
1. As a developer
2. I want to run every vendor without max products limit
3. So that the complete data of all formwares are available

## Acceptance criteria
* We have all the meta data from all the products from all the vendors scraped and mapped to mySQL database

## Definition of done (DoD)
* All the acceptance criteria have been met
* The code has been merged with the main one
* The documentation and Bill of Materials have been updated
* The code is complete and uploaded in GitHub
* Functionality has been reviewed

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by kirilzilla** [comment]
7 vendors have issues, about 11 vendors work:
Rockwell, Netgear take very long (1,5h for Rock - 8h Net ) , ABB returns 1 product, Belkin errors out

+-------------------+
 │| manufacturer      |
 │+-------------------+
 │| ABB               |
 │| AVM               |
 │| foscam            |
 │| Gigaset           |
 │| Qnap              |
 │| SchneiderElectric |
 │| Swisscom          |
 │| Synology          |
 │| TP-Link           |
 │| Trendnet          |
 │| Zyxel             |
 │+-------------------+

**Comment by kirilzilla** [comment]
│mysql> select count(*), manufacturer  from products group by manufacturer ;
│+----------+-------------------+
│| count(*) | manufacturer      |
│+----------+-------------------+
│|        1 | ABB               |
│|      293 | AVM               |
│|      300 | foscam            |
│|       21 | Gigaset           |
│|      989 | Qnap              |
│|      524 | SchneiderElectric |
│|       10 | Swisscom          |
│|      367 | Synology          |
│|      480 | TP-Link           |
│|        1 | Trendnet          |
│|        9 | Zyxel             |
│+----------+-------------------+
│11 rows in set (0.00 sec)

**Comment by m-1-k-3** [comment]
Could you post updated numbers?
Wondering about ABB, Trendnet and Zyxel ...
