### ISSUE TITLE
Core should have funtionality to compare products/firmware

### ISSUE THREAD

**Issue by Deepakraj8055** [amosproj/amos2022ws01-firmware-scraper#45]
## User story
1. As a user 
2. When i run the core
3.  Then the core should be able to compare the product catalog with all historised firmware data already available

## Acceptance criteria
* Find appropriate comaprision method
* Should run as fast and effecient as possible
* Write python test for finding new products
* if no new products found skip downloading
* Display information about the number of items being dowloaded and comapred (logging)

## Definition of done (DoD)
* All the acceptance criteria have been met
* The code has been merged with the main one
* The documentation and Bill of Materials have been updated
* The code is complete and uploaded in GitHub
* Functionality has been reviewed
* The tests to ensure the feature is working have been created

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by kirilzilla** [comment]
using LEFT JOIN Method.
