### ISSUE TITLE
Implement tools for code check

### ISSUE THREAD

**Issue by Deepakraj8055** [amosproj/amos2022ws01-firmware-scraper#47]
## User story
1. As a developer
2. When i commit code to github 
3. Then i Want the code to run through code checking 

## Acceptance criteria
* Ex. pytest flake8 black isort (optioal : safety bandit) are passed
* If tests are unsuccessfull the developer is responsible to correct and commit the correct one

## Definition of done (DoD)
* All the acceptance criteria have been met
* The code has been merged with the main one
* The documentation and Bill of Materials have been updated
* The code is complete and uploaded in GitHub
* Functionality has been reviewed

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by kirilzilla** [comment]
developers agrred on using these packages locally for code check
pytest flake8 black isort safety bandit
